FROM node:16

WORKDIR /usr/src/app

COPY --chown=node:node . .

RUN npm ci

ENV VITE_BACKEND_URL="http://localhost:3000"

RUN npm run build

RUN npm install -g serve

USER node

CMD ["serve", "dist"]
